# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4804ddd826f11410ff16bcc4e4a6681a51c4ba7cd9ff4a5f057dc3746a975d8808f8f7d253310bb2fc9d8c520665d459452f67bb04cb443ca4d99c30488380a3

test:
  secret_key_base: bf0e934c6b0e96a3c53da377a8e35a2e6b25f57e6d7f25b4a9d242db2e81b7908d9d0198ea84e10852f037e6630cec3d7cb7fee8b166cce74349844d3c663866

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
